---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stats/current
    - export NODEJS=/opt/alt/alt-nodejs22/root/usr/bin/node
    - export NPM=/opt/alt/alt-nodejs22/root/usr/bin/npm
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - echo "Installing npm dependencies..."
    - $NPM install --production=false
    - echo "Building frontend assets..."
    - $NPM run build
    - echo "Clearing Laravel caches..."
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan config:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan cache:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan view:clear
    - echo "Optimizing for production..."
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php83/root/usr/bin/php artisan view:cache
    - echo "Ensuring build symlink is correct..."
    - cd /home/stats/public_html
    - if [ ! -L build ] || [ "$(readlink build)" != "/home/stats/current/public/build" ]; then rm -rf build && ln -s /home/stats/current/public/build build && echo "Build symlink updated"; fi
    - echo "Deployment complete! Site: https://stats.squashplayers.app/"

